### ISSUE TITLE
Question: play-json compatibility

### ISSUE THREAD

**Issue by idot** [scala-tsi/scala-tsi#107]
Hello,
I apologize in advance for asking without trying it out first. But when I generate my Json with play-json, will your generated typescript classes be compatible with play-json?

I mostly generate it with (the XYRows are generated by scala-slick or are hand created case-classes):
```
  implicit val encoder: ai.x.play.json.NameEncoder = ai.x.play.json.CamelToSnakeNameEncoder()
  implicit val samplesFormat = Jsonx.formatCaseClass[SamplesRow]
  implicit val readmodesFormat = Json.format[ReadmodesRow]
```

I could also switch to another scala-json library that you suggest if I can then use your generator.

thank you very much,
ido

**Comment by dhoepelman** [comment]
scala-tsi will use field names identical to your case class field names. This is the same behavior as play-json and  xdotai:play-json-extensions.

Because you change camel case to snake name in fields that won't work (`CamelToSnakeNameEncoder()`). Remove that and it will do the right thing.

Here is how you could do that if you still want to: #107
